//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanchasPorHorarios
    {
        public int id { get; set; }
        public Nullable<int> idHorario { get; set; }
        public Nullable<int> idCancha { get; set; }
        public Nullable<int> idEstado { get; set; }

        public virtual Cancha Cancha { get; set; }
        public virtual Horario Horario { get; set; }
    }
}
