//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeportesPorDeportistas
    {
        public int id { get; set; }
        public Nullable<int> idDeportista { get; set; }
        public Nullable<int> idDeporte { get; set; }
    
        public virtual Deporte Deporte { get; set; }
        public virtual Deportista Deportista { get; set; }
    }
}
