//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleValoracionDeportista
    {
        public int id { get; set; }
        public Nullable<int> nroEstrellas { get; set; }
        public Nullable<int> idTipoValoracion { get; set; }
        public Nullable<int> idValoracion { get; set; }
    
        public virtual TipoValoracionDeportista TipoValoracionDeportista { get; set; }
        public virtual ValoracionDeportista ValoracionDeportista { get; set; }
    }
}
