//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.DeportistasPorEquipos = new HashSet<DeportistasPorEquipos>();
            this.EncuentroDeportivo = new HashSet<EncuentroDeportivo>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> capacidad { get; set; }
        public Nullable<int> nroDeportistasActual { get; set; }
        public Nullable<double> promedioEstrellas { get; set; }
        public Nullable<int> idEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeportistasPorEquipos> DeportistasPorEquipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuentroDeportivo> EncuentroDeportivo { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
