//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class estadisticaComplejo
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string deporte { get; set; }
    
        public virtual DIM_TIEMPO DIM_TIEMPO { get; set; }
    }
}
