//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvitacionEncuentro
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
        public Nullable<int> idEncuentro { get; set; }
        public Nullable<int> idInvitado { get; set; }
    
        public virtual Deportista Deportista { get; set; }
        public virtual EncuentroDeportivo EncuentroDeportivo { get; set; }
    }
}
