//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    
<<<<<<< HEAD:HayEquipo/CapaEntidades/sp_NotificacionDao_mostrarNotificaciones_Result.cs
    public partial class sp_NotificacionDao_mostrarNotificaciones_Result
    {
        public int id { get; set; }
        public string emisor { get; set; }
        public string texto { get; set; }
        public Nullable<int> idEncuentro { get; set; }
        public string estado { get; set; }
=======
    public partial class Mapa
    {
        public int id { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
>>>>>>> Agu_Branch:HayEquipo/CapaEntidades/Mapa.cs
    }
}
