//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
<<<<<<< HEAD:HayEquipo/CapaEntidades/ReporteCantidadDeportexFecha_Result.cs
    public partial class ReporteCantidadDeportexFecha_Result
    {
        public string Deporte { get; set; }
        public Nullable<int> año { get; set; }
        public string mes { get; set; }
        public Nullable<int> CantidadPartidos { get; set; }
=======
    public partial class Password
    {
        public int id { get; set; }
        public byte[] pwdUsuario { get; set; }
        public byte[] pwdEncuentro { get; set; }
>>>>>>> Agu_Branch:HayEquipo/CapaEntidades/Password.cs
    }
}
