//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fechaReserva { get; set; }
        public Nullable<System.TimeSpan> horaReserva { get; set; }
        public Nullable<int> idEncuentroDeportivo { get; set; }
        public Nullable<int> idEstado { get; set; }
    }
}
