//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValoracionDeportista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ValoracionDeportista()
        {
            this.DetalleValoracionDeportista = new HashSet<DetalleValoracionDeportista>();
        }
    
        public int id { get; set; }
        public Nullable<int> idDeportista { get; set; }
        public string reseña { get; set; }
        public Nullable<double> promedioEstrellas { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
    
        public virtual Deportista Deportista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleValoracionDeportista> DetalleValoracionDeportista { get; set; }
    }
}
