//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesion
    {
        public int id { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<System.DateTime> horaInicio { get; set; }
        public Nullable<System.DateTime> horaFin { get; set; }
        public Nullable<int> idEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
